name: y1000_plus_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.14
  - pip>=23
  - numpy>=1.23
  - scipy>=1.9
  - pandas>=1.5
  - matplotlib>=3.6
  - seaborn>=0.10
  - biopython>=1.79
  - lxml>=4.9
  - matplotlib-venn>=0.11
  - ipykernel>=6
  - ipython>=7
  - jupyter>=1.0
  - notebook>=6.5
  - ipywidgets>=7
  - plotly>=4.8
  - statsmodels
  - patsy
  - requests
  - beautifulsoup4
  - bs4
  - ete3
  - plotly
  - retrying
  - squarify
  - pyqt
  - qtpy
  - pillow
  - cffi
  - cryptography>=39
  - mistune
  - defusedxml
  - bleach
  - colorama
  - decorator
  - attrs
  - backcall
  - jinja2
  - prompt_toolkit
  - pygments
  - traitlets
  - widgetsnbextension
  - zeromq
  - pyopenssl
  - pyparsing
  - urllib3
  - six
  - send2trash>=1.8
  - wheel
  - setuptools
  - pip:
      - argcomplete>=1.11
      - argh>=0.26
      - future>=0.18
      - gffutils>=0.10
      - pyfaidx>=0.5
      - simplejson>=3.17

